name: Simple CI trigger

on:
  workflow_call:

jobs:
  Build-WebApp:
    name: Build simple node webapp
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: run tests
      run: ls -ltr
    - name: Get current date and time format
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
    - name: echo current date and time
      run: echo ${{ steps.date.outputs.date }}
    # - name: setup latest app version
    #   id: version
    #   if: ${{ github.event.ref == 'refs/heads/main' || github.event.ref == 'refs/heads/develop' }}        
    #   run: |
    #     if [[ ${{ github.event.ref_name }} == 'main' ]]; then
    #       echo "It is main branch. hence, we will create the release tag"
    #       version="1.0.0"
    #       echo "::set-output name=version::$version"
    #     elif [[ ${{ github.event.ref_name }} == 'develop' ]]; then
    #        echo "It is develop branch. hence, we will create a snapshot tag"
    #        version="1.0.0.SNAPSHOT-${{ steps.date.outputs.date }}"
    #        echo "::set-output name=version::$version"
    #     fi
    # - name: Display calculated version
    #   run: echo "Calculated version is ${{ steps.version.outputs.version }}"

    # - name: Push Docker Image to Docker Hub
    #   uses: docker/build-push-action@v5
    #   with:
    #     push: true
    #     tags: simple-node-webapp
